---
- name: Mount Network Share
  hosts: all
  tasks:
     - name: Unmount {{ SHARE_NAME }}
       mount:
         path: "/mnt/{{ SHARE_NAME }}"
         state: unmounted
       become: true

     - name: Create credential file (used for fstab entry)
       copy:
         content: |
           username="{{ USERNAME }}"
           password="{{ PASSWORD }}"
         dest: /mnt/.credential
         mode: 0600
       become: true
 
     - name: Create fstab entry for {{ SHARE_NAME }}
       mount: 
         state: present 
         fstype: cifs 
         opts: "credentials=/mnt/.credential,file_mode=0777,dir_mode=0777" 
         src: "{{ SHARE_PATH }}" 
         path: "/mnt/{{ SHARE_NAME }}"
       become: true

     - name: Creates /mnt/{{ SHARE_NAME }}
       file:
         path: "/mnt/{{ SHARE_NAME }}"
         state: directory
       become: true    
  
     - name: Mount {{ SHARE_NAME }}
       shell: |
         mount '/mnt/{{ SHARE_NAME }}'
       become: true
 