# Creates pihole directory
# ansible-playbook pihole/manual-config/ansible-create-directories-local.yaml -i ansible/inventory -u pi
---
- name: Mount Network Share
  hosts: all
  tasks:
     - name: Creates /etc/pihole
       file:
         path: "/etc/pihole"
         state: directory
       become: true
     - name: Creates /etc/dnsmasq
       file:
         path: "/etc/dnsmasq"
         state: directory
       become: true    
