# Deploys a single pihole replica accessibel via 192.168.1.160:8000/admin
#           
---
# Define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          value: "secret"
        volumeMounts:
        - name: pihole-volume
          mountPath: "/etc/pihole"
        - name: dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: pihole-volume
        persistentVolumeClaim:
          claimName: pihole-volume-claim
      - name: dnsmasq-volume
        persistentVolumeClaim:
          claimName: dnsmasq-volume-claim
